version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Hospiol@123
      MYSQL_DATABASE: hospiol
      MYSQL_USER: hospiol
      MYSQL_PASSWORD: Hospiol@123
    volumes:
      - ./db_data:/var/lib/mysql
