version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html  # Mount your PHP application source code here

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Hospiol@123
      MYSQL_DATABASE: hospioldb
    ports:
      - "3306:3306"
